#
# Based on https://hub.docker.com/_/sonarqube
#
version: "3.7"
services:
  sonarscanner:
    container_name: sonarscanner
    image: sonarsource/sonar-scanner-cli
    networks:
      - sonarnet
    volumes:
      - ./repo/SonarTS-example:/usr/src

networks:
  sonarnet:

